name: Python application

on:
  push:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Toto
      run: echo $RUNNER_TOOL_CACHE
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        python --version

  gpu:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Toto
      run: echo $RUNNER_TOOL_CACHE
    - run: python --version
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        python --version
